### ISSUE TITLE
License all images

### ISSUE THREAD

**Issue by fulldecent** [AtanasProject/monitor-tech-v2#22]
Work plan

- [x] Identify list of licensed images
-  [ ] get licenses (@fulldecent)
- [ ] edit / minify as needed

**Comment by ultraasi-atanas** [comment]
Here is the image list
Including the two logos that we produced:
https://docs.google.com/spreadsheets/d/1TNN1BGo2fv42NweYmJsDj5ymUeiUvb_vzQ074imUnL4/edit#gid=1386834576

**Comment by ultraasi-atanas** [comment]
@fulldecent please take a look at the spreadsheet document with links and advise

**Comment by fulldecent** [comment]
For @Raza403

**Comment by ultraasi-atanas** [comment]
Apologies @Raza403 @fulldecent just seeing this - somehow it got lost as updates are going to my other email account. We will review and merge Tuesday, the latest

**Comment by ultraasi-atanas** [comment]
It's really beautiful - all merged - great work with the images @Raza403 - check it out @fulldecent atanasproject.github.io/monitor-tech-v2/
